networks:
  rag_network:
    driver: bridge

services:
  rag-app:
    build: .
    container_name: rag_system_app
    ports:
      - "8501:8501"
    volumes:
      - ./app/data:/app/app/data
      - ./.env:/app/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8088
    depends_on:
      - weaviate
    networks:
      - rag_network
    restart: unless-stopped

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8088'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.34.0
    ports:
    - 8088:8088
    - 50051:50051
    volumes:
    - ./data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'none'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - rag_network

